[project]
name = "crace"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "dask[distributed]>=2025.12.0",
    "geopandas>=1.1.1",
    "llvmlite>=0.43.0",  # Fix uv resolution bug, see https://github.com/astral-sh/uv/issues/9413
    "numpy>=2.3.5",
    "odc-geo>=0.4.10",
    "rioxarray>=0.19.0",
    "sparse>=0.17.0",
    "xarray>=2025.11.0",
]

[dependency-groups]
dev = [
    "hypothesis[numpy]>=6.150.0",
    "pre-commit>=4.5.1",  # Not needed for uv (?)
    "pytest>=9.0.1",
    {include-group = "doc"},
    {include-group = "interactive"},
    {include-group = "type"},
]
doc = [
    "furo>=2025.12.19",
    "sphinx>=9.0.4",
    "sphinx-remove-toctrees>=1.0.0.post1",
]
interactive = [
    "cartopy>=0.25.0",
    "matplotlib>=3.10.8",
    "notebook>=7.5.0",
]
type = [
    "mypy>=1.19.1",
    "pandas-stubs>=2.3.3.260113",
    "types-geopandas>=1.1.2.20251224",
]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = ["C90", "E", "F", "I", "W", "PL", "N"]
exclude = ["*.ipynb"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.pylint]
max-args = 8

[tool.ruff.format]
exclude = ["scripts/*.ipynb"]
